#============== kafka ===================
# 指定kafka 代理地址，可以多个
spring:
  kafka:
    bootstrap-servers: 106.12.50.184:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#redis-cluster配置
  redis:
    database: 0
    password: cynic
    commandTimeout: 10000  #redis操作的超时时间
    expireSeconds: 120
    cluster:
      nodes: 106.12.50.184:7001,106.12.50.184:7002,106.12.50.184:7003,106.12.50.184:7004,106.12.50.184:7005,106.12.50.184:7006
      max-redirects: 6
    jedis:
      pool:
        max-active: 50     # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10       # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
    timeout: 3000



#============== elastic-job ===================
# 指定注册中心地址 节点名称，可以多个
regCenter:
  serverList: 106.12.50.184:2181
  namespace: elastic-job-lite-springboot
stockJob:
  cron: 0 0 * * * ?                                 #job执行定时cron函数 /一小时执行一次
  shardingTotalCount: 6                             #分片总数
  shardingItemParameters: 0=slice1,1=slice2,2=slice3,3=slice4,4=slice5,5=slice6           #用户定义分片含义  每个分片可定义个性化含义


